version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: agricultural_platform_db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: agricultural_platform
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js:ro
    networks:
      - agricultural_network

  # Backend API Server
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: agricultural_platform_api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://root:rootpassword@mongodb:27017/agricultural_platform?authSource=admin
      JWT_SECRET: your-production-jwt-secret-change-this
      CLIENT_URL: http://localhost:3000
      WEATHER_API_KEY: your-openweathermap-api-key
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - agricultural_network
    volumes:
      - ./server/uploads:/app/uploads

  # Frontend React Application
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: agricultural_platform_client
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:5000/api
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - agricultural_network

volumes:
  mongodb_data:

networks:
  agricultural_network:
    driver: bridge